# .github/workflows/sync-fork.yml
name: Sync fork (no-CI)

on:
  schedule:
    - cron: '23 3 * * *'   # daily at 03:23 UTC
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: sync-fork
  cancel-in-progress: true

jobs:
  sync:
    if: ${{ github.event.repository.fork == true }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Sync default branch from upstream (parent) to this fork
        run: |
          gh repo sync "${GITHUB_REPOSITORY}"
      - name: Show the last few commits after sync (for logs)
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git -C "$GITHUB_WORKSPACE" log --oneline -5 || true
